# -*- coding: utf-8 -*-

from . import dh_transit_dossier
from . import dh_transit_regime
from . import dh_transit_bureau
from . import dh_transit_arrondissement
from . import dh_transit_lieustockage
from . import dh_res_partner
from . import dh_transit_dossier_details
from . import dh_res_country
from . import dh_transit_mode_transport
from . import dh_transit_type_transport
from . import dh_transit_docs
from . import dh_transit_type_annexation
from . import dh_transit_facture
from . import dh_transit_uom
from . import dh_transit_mode_paiement
from . import dh_transit_terminal
from . import dh_transit_unite
from . import dh_transit_charges
from . import dh_transit_charges_lines
from . import dh_transit_departement
from . import dh_transit_circuit_validation
from . import dh_transit_priorite
from . import dh_type_interlocuteur
from . import res_city
from . import dh_etat_tasks
from . import dh_puerto_settings
from . import dh_transit_parametre_annexation
from . import dh_transit_parametres_charges
from . import dh_transit_parametres_charge_lines
from . import station
from . import dh_contenat
from . import dh_transite_facture_lines
from . import fleet_vehicle
from . import dh_wizard_transit_dossier
from . import dh_product_category
from . import dh_wizard_importer_facture
